import pytest
from src.bacon import *

plaintext = """AAABAABBBAABBABAABBABAAABAAAAABAABBBABAAABABBAAAAABAA
BBABAAAABBBAABBABBAABA BBAAAABBBABABAA
AABBBAAAAABABABAABAA AABABABBBABABAAABBABAAABB
BAABBAABBBAABAA
BAABBBAAABAABAAAAAAABAABABABAABAAABAABAA ABBBAAABAB
BAABBAABBBAABAA BAABAABAAAABABBBABABAABAABAAAB
BAABABAABBAAAAABAAAB AAAABBAAABABAAAABBABAABBA
BAABBAABBBABAAABAABA AAABAABBBAAAABBAABAA
BABBAABBBABAAABAAABB BAABBABBBA
ABAABAABAAABBABABBABBBAAA ABBBABAAAB
BAABBAABAABAABABAABA BAABBABBBA AABBAAABAABAABB
BBAAAABBBABABAABAAAB ABBBBBAAABABAAABBAABAABAA
AABBABABAAAAABAAAABAABAAA"""
ciphertext = """congratulations you have found the treasure of the silver star bring this code word to jenny or tess to get your prize gucci"""


def test_bacon_encode():
    assert bacon_encode(plaintext) == ciphertext


def test_bacon_decode():
    assert bacon_encode(ciphertext) == plaintext
